# Type dvc-help in this file and hit enter to get more information on how the extension can help to setup pipelines
stages:
  train:
    cmd: python functa4eo/_src/config.py
    deps:
    - functa4eo/_src/config.py

plots:
- step vs loss:
    template: simple
    x: step
    y:
      dvclive/plots/metrics/loss.tsv: loss
- dvclive/plots/metrics:
    x: step
    y:
      dvclive/plots/metrics/loss.tsv: loss
metrics:
- dvclive/metrics.json
